In [1]:
# Question 1: Introduction of PyTorch Tensors and Basic Operations

import torch
import numpy as np

print("=" * 50)
print("Question 1: PyTorch Tensors and Basic Operations")
print("=" * 50)

# a) Understanding PyTorch tensors, initialization methods, and data types
print("\na) Tensor Initialization Methods and Data Types:")
print("-" * 50)

# Create tensors using different methods
t1 = torch.tensor([1, 2, 3, 4, 5])
print(f"From list: {t1}, dtype: {t1.dtype}")

t2 = torch.zeros((3, 3))
print(f"\nZeros tensor:\n{t2}")

t3 = torch.ones((2, 4))
print(f"\nOnes tensor:\n{t3}")

t4 = torch.rand((2, 3))
print(f"\nRandom tensor:\n{t4}")

t5 = torch.arange(0, 10, 2)
print(f"\nArange tensor: {t5}")

t6 = torch.linspace(0, 1, 5)
print(f"\nLinspace tensor: {t6}")

# Different data types
t_int = torch.tensor([1, 2, 3], dtype=torch.int32)
t_float = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
t_double = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
print(f"\nInt32 tensor: {t_int}, dtype: {t_int.dtype}")
print(f"Float32 tensor: {t_float}, dtype: {t_float.dtype}")
print(f"Float64 tensor: {t_double}, dtype: {t_double.dtype}")

# b) Tensor operations: arithmetic, broadcasting, indexing, and reshaping
print("\n\nb) Tensor Operations:")
print("-" * 50)

# Arithmetic operations
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])
print(f"a = {a}")
print(f"b = {b}")
print(f"Addition: {a + b}")
print(f"Subtraction: {a - b}")
print(f"Multiplication: {a * b}")
print(f"Division: {a / b}")

# Broadcasting
c = torch.tensor([[1, 2, 3], [4, 5, 6]])
d = torch.tensor([10, 20, 30])
print(f"\nBroadcasting:")
print(f"c =\n{c}")
print(f"d = {d}")
print(f"c + d =\n{c + d}")

# Indexing
e = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"\nIndexing:")
print(f"Tensor e =\n{e}")
print(f"e[0]: {e[0]}")
print(f"e[:, 1]: {e[:, 1]}")
print(f"e[1, 2]: {e[1, 2]}")
print(f"e[0:2, 1:3]:\n{e[0:2, 1:3]}")

# Reshaping
f = torch.arange(12)
print(f"\nReshaping:")
print(f"Original: {f}")
print(f"Reshaped (3, 4):\n{f.reshape(3, 4)}")
print(f"Reshaped (2, 6):\n{f.reshape(2, 6)}")
print(f"View (4, 3):\n{f.view(4, 3)}")

# c) Automatic differentiation using PyTorch's Autograd system
print("\n\nc) Automatic Differentiation (Autograd):")
print("-" * 50)

# Create tensors with gradient tracking
x = torch.tensor(2.0, requires_grad=True)
y = torch.tensor(3.0, requires_grad=True)

# Define a function: z = x^2 + y^3
z = x**2 + y**3
print(f"x = {x.item()}, y = {y.item()}")
print(f"z = x^2 + y^3 = {z.item()}")

# Compute gradients
z.backward()
print(f"\nGradients:")
print(f"dz/dx = 2x = {x.grad.item()}")
print(f"dz/dy = 3y^2 = {y.grad.item()}")

# Another example with matrix operations
a = torch.randn(3, 3, requires_grad=True)
b = torch.randn(3, 3, requires_grad=True)
c = a * b
out = c.sum()
out.backward()
print(f"\nMatrix multiplication gradients computed.")
print(f"Gradient shape for a: {a.grad.shape}")
print(f"Gradient shape for b: {b.grad.shape}")

print("\n" + "=" * 50)
print("Question 1 Complete")
print("=" * 50)

Question 1: PyTorch Tensors and Basic Operations

a) Tensor Initialization Methods and Data Types:
--------------------------------------------------
From list: tensor([1, 2, 3, 4, 5]), dtype: torch.int64

Zeros tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Ones tensor:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Random tensor:
tensor([[0.2841, 0.4287, 0.7096],
        [0.9263, 0.3294, 0.1768]])

Arange tensor: tensor([0, 2, 4, 6, 8])

Linspace tensor: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

Int32 tensor: tensor([1, 2, 3], dtype=torch.int32), dtype: torch.int32
Float32 tensor: tensor([1., 2., 3.]), dtype: torch.float32
Float64 tensor: tensor([1., 2., 3.], dtype=torch.float64), dtype: torch.float64


b) Tensor Operations:
--------------------------------------------------
a = tensor([1, 2, 3, 4])
b = tensor([5, 6, 7, 8])
Addition: tensor([ 6,  8, 10, 12])
Subtraction: tensor([-4, -4, -4, -4])
Multiplication: tensor([ 5, 12, 21, 32])
Divi

In [2]:
# Question 3: Write a program to implement AND OR gates using Perceptron

import numpy as np

class Perceptron:
    def __init__(self, input_size, learning_rate=0.1, epochs=100):
        self.weights = np.zeros(input_size + 1)  # +1 for bias
        self.lr = learning_rate
        self.epochs = epochs

    def activation(self, x):
        return 1 if x >= 0 else 0

    def predict(self, x):
        # z = w1*x1 + w2*x2 + ... + bias
        z = np.dot(x, self.weights[1:]) + self.weights[0]
        return self.activation(z)

    def train(self, X, y):
        for _ in range(self.epochs):
            for inputs, label in zip(X, y):
                prediction = self.predict(inputs)
                error = label - prediction
                # Update weights: w = w + lr * error * input
                self.weights[1:] += self.lr * error * inputs
                self.weights[0] += self.lr * error


def print_gate_results(title, model, inputs):
    print(f"{'=' * 12} {title} {'=' * 12}")
    print(f"{'Input 1':<8}{'Input 2':<8}{'Output':<8}")
    print('-' * 24)
    for x in inputs:
        print(f"{x[0]:<8}{x[1]:<8}{model.predict(x):<8}")
    print()


# Data for Gates
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y_and = np.array([0, 0, 0, 1])
y_or = np.array([0, 1, 1, 1])

# AND Gate
p_and = Perceptron(input_size=2)
p_and.train(X, y_and)
print_gate_results('AND Gate', p_and, X)

# OR Gate
p_or = Perceptron(input_size=2)
p_or.train(X, y_or)
print_gate_results('OR Gate', p_or, X)

============ AND Gate ============
Input 1 Input 2 Output  
------------------------
0       0       0       
0       1       0       
1       0       0       
1       1       1       

============ OR Gate ============
Input 1 Input 2 Output  
------------------------
0       0       0       
0       1       1       
1       0       1       
1       1       1       



In [3]:
# Question 4: Implementation of XOR Problem using PyTorch Neural Network

import torch
import torch.nn as nn
import torch.optim as optim

class XORModel(nn.Module):
    def __init__(self):
        super(XORModel, self).__init__()
        # XOR requires a hidden layer because it's not linearly separable
        self.layer1 = nn.Linear(2, 2)
        self.activation = nn.Sigmoid()
        self.layer2 = nn.Linear(2, 1)

    def forward(self, x):
        x = self.activation(self.layer1(x))
        x = self.activation(self.layer2(x))
        return x


# XOR Data
X_xor = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float32)
Y_xor = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)

model_xor = XORModel()
criterion = nn.MSELoss()
optimizer = optim.SGD(model_xor.parameters(), lr=0.1)

print(f"{'=' * 10} XOR Problem {'=' * 10}")
for epoch in range(5000):
    outputs = model_xor(X_xor)
    loss = criterion(outputs, Y_xor)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 1000 == 0:
        print(f'Epoch {epoch + 1:5d}: Loss = {loss.item():.4f}')

print('\nResults:')
print(f"{'Input':<16}{'Probability':<16}{'Prediction':<12}")
print('-' * 44)
with torch.no_grad():
    predicted = model_xor(X_xor)
    for x_val, prob in zip(X_xor, predicted):
        prediction = int(prob.item() > 0.5)
        print(f"{str(tuple(int(v) for v in x_val)):<16}{prob.item():<16.4f}{prediction:<12}")

========== XOR Problem ==========
Epoch  1000: Loss = 0.2500
Epoch  2000: Loss = 0.2500
Epoch  3000: Loss = 0.2500
Epoch  4000: Loss = 0.2500
Epoch  5000: Loss = 0.2500

Results:
Input           Probability     Prediction  
--------------------------------------------
(0, 0)          0.5006          1           
(0, 1)          0.5003          1           
(1, 0)          0.4999          0           
(1, 1)          0.4996          0           


In [4]:
# Question 5: Implement Simple Neural Network to solve regression problem
# House Price Prediction using house_data.csv

import pandas as pd
import torch
import torch.nn as nn
import torch.optim as optim
import os

# Load Data
csv_path = 'house_data.csv'

# Check if file exists, if not look in likely location
if not os.path.exists(csv_path):
    possible_path = 'c:/new pc/College Labs VI/DL lab/Lab 1/house_data.csv'
    if os.path.exists(possible_path):
        csv_path = possible_path

print(f"{'=' * 10} House Price Prediction {'=' * 10}")
print(f"Data source: {csv_path}\n")

try:
    df = pd.read_csv(csv_path)

    x_raw = df[['bedrooms', 'sqft_living']].values
    y_raw = df[['price']].values

    # Data Normalization (Min-Max Scaling)
    x_min = x_raw.min(axis=0)
    x_max = x_raw.max(axis=0)
    y_min = y_raw.min(axis=0)
    y_max = y_raw.max(axis=0)

    x_scaled = (x_raw - x_min) / (x_max - x_min)
    y_scaled = (y_raw - y_min) / (y_max - y_min)

    X_reg = torch.tensor(x_scaled, dtype=torch.float32)
    Y_reg = torch.tensor(y_scaled, dtype=torch.float32)

    # Model Definition from Diagram
    class RegressionNN(nn.Module):
        def __init__(self):
            super(RegressionNN, self).__init__()
            self.hidden = nn.Linear(2, 2)
            self.output = nn.Linear(2, 1)
            self.activation = nn.Sigmoid()

        def forward(self, x):
            hidden_out = self.activation(self.hidden(x))
            return self.activation(self.output(hidden_out))

    model_reg = RegressionNN()
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model_reg.parameters(), lr=0.1)

    print('Training model...')
    epochs = 1500
    for epoch in range(epochs):
        outputs = model_reg(X_reg)
        loss = criterion(outputs, Y_reg)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if (epoch + 1) % 300 == 0:
            print(f'Epoch {epoch + 1:4d}: Loss = {loss.item():.6f}')

    # Evaluation
    model_reg.eval()
    with torch.no_grad():
        predicted_scaled = model_reg(X_reg)
        # Inverse transform to get actual prices
        predicted_prices = predicted_scaled.numpy() * (y_max - y_min) + y_min

        print('\nSample predictions (top 5 rows):')
        print(f"{'Bedrooms':<10}{'Sqft':<12}{'Predicted':<16}{'Actual':<16}")
        print('-' * 54)
        for bedrooms, sqft, pred, actual in zip(
            x_raw[:5, 0],
            x_raw[:5, 1],
            predicted_prices[:5, 0],
            y_raw[:5, 0],
        ):
            print(f"{int(bedrooms):<10}{int(sqft):<12}{pred:<16.2f}{actual:<16.2f}")

except Exception as exc:
    print(f'Error loading data or training: {exc}')

========== House Price Prediction ==========
Data source: house_data.csv

Training model...
Epoch  300: Loss = 0.006624
Epoch  600: Loss = 0.005848
Epoch  900: Loss = 0.005793
Epoch 1200: Loss = 0.005775
Epoch 1500: Loss = 0.005754

Sample predictions (top 5 rows):
Bedrooms  Sqft        Predicted       Actual          
------------------------------------------------------
3         1340        383293.11       313000.00       
5         3650        958236.43       2384000.00      
3         1930        472475.72       342000.00       
3         2000        485456.56       420000.00       
4         1940        470350.83       550000.00       
